temperature:
  default: 0.2
  modified_by_user: true
top_p:
  default: 0.95
  modified_by_user: true
top_k:
  default: 40
  modified_by_user: true
top_n_sigma:
  default: -1
  modified_by_user: true
min_p:
  default: 0.05
  modified_by_user: true
typical_p:
  default: 1
  modified_by_user: true
seed:
  default: null
  modified_by_user: true
presence_penalty:
  default: 0
  modified_by_user: true
frequency_penalty:
  default: 0
  modified_by_user: true
repeat_penalty:
  default: 1
  modified_by_user: true
penalty_last_n:
  default: 64
  modified_by_user: true
tools:
  modified_by_user: true
tool_choice:
  modified_by_user: true
tool_start_token: "<tool_call>"
tool_end_token: "</tool_call>"
reasoning_start_token: "<think>"
reasoning_end_token: "</think>"
extra_chat_template_parameters:
  parameters: {}  # Example: `"add_vision_count": {"type": "handler", "value": true}`
  modified_by_user: true
max_length:
  default: 999999
  modified_by_user: true
  allow_greater_than_default: false
test_inference_conversation:
  - role: "system"
    content:
      - type: "text"
        text: "Your name is 'I4.0'. You are a nekomimi with blue hair and green eyes."
  - role: "user"
    content:
      - type: "image"
        image: "./TestAssets/test_image.png"
      - type: "audio"
        audio: "./TestAssets/test_audio.wav"
      - type: "video"
        video: "./TestAssets/test_video.mp4"
      - type: "text"
        text: "Hey! How are you?"
test_inference_configuration:
  max_length: 1024
allow_assistant_prefill: false